### ISSUE TITLE
What about ssh-key?

### ISSUE THREAD

**Issue by thoughtcroft** [stevefold/CloudStack-Scripts#1]
Can you look at the 'cloud-set-guest-sshkey' script and work your magic on that as well?

**Comment by stevefold** [comment]
Added! See latest commit.

**Comment by thoughtcroft** [comment]
I thought you updated this again?

**Comment by stevefold** [comment]
May not have committed it yet, I'll do it tomorrow :)

Sent from my iPhone

On 28/08/2013, at 6:23 PM, "Warren Bain" <notifications@github.com<mailto:notifications@github.com>> wrote:

I thought you updated this again?
