### ISSUE TITLE
Differences in DHCP folder evaluation b/w scripts

### ISSUE THREAD

**Issue by thoughtcroft** [stevefold/CloudStack-Scripts#2]
Steve,

There is a difference b/w the ssh_key and the password scripts in how DHCP folders are parsed etc.  Which one is right and should they even be different since both scripts have to talk to the same virtual router?

Wazza

**Comment by stevefold** [comment]
Ssh_key variant is a more ‘advanced’ script comprised of the lessons and techniques learnt as I improved the others (password reset). Ssh_key is also set to be a more ‘universal’ script that can be applied across Debian/Ubuntu and CentOS/Fedora OS’s without relying on separate scripts per OS as I do today with the Password scripts.

The focus of this is to of course improve the effectiveness and efficiency of future deployments and even developments by making it a ‘one-size-fits-all’ script.

Regards,
Steve
